spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservice
    username: root
    password: Omkar66527
    driver-class-name: com.mysql.cj.jdbc.Driver
   
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
      
 spring:
  data:
    mongodb:
      database: ProductService
      host: localhost
      port: 27017
